name: Run Postman Tests on Push

on:
  push:
    branches: [ main ]  # o el nombre de tu rama

jobs:
  postman-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Postman collection
      uses: actions/setup-node@v3

    - name: Install Newman (Postman CLI)
      run: npm install -g newman

    - name: Run tests with Newman
      run: | 
        newman run .github/tests/Test_Post_Postman.json \
          --environment .github/tests/TFG_Eala.postman_environment.json
          --env-var "email=${{ secrets.TEST_USER_EMAIL }}" \
          --env-var "password=${{ secrets.TEST_USER_PSWD }}"